<?php
/**
 * Created by PhpStorm.
 * User: SimonaThrussell
 * Date: 13/09/2018
 * Time: 11:23
 */

class Device
{
    public $devicetype;
    public $devicestorage;
    public $devicemodel;
    public $devicecolour;
    public $devicecondition;
    public $devicememory;
    public $IMEI;
    public $warranty;


        public function __construct($devicetype, $devicestorage,$devicemodel,$devicecolour,$devicecondition,$devicememory)
        {
            $this->devicetype=$devicetype;
            $this->devicestorage=$devicestorage;
            $this->devicemodel=$devicemodel;
            $this->devicecolour=$devicecolour;
            $this->devicecondition=$devicecondition;
            $this->devicememory=$devicememory;




        }

        public function GetDeviceInfo()
        {
            echo $this->devicetype."</br>";
            echo $this->devicestorage."</br>";
            echo $this->devicemodel."</br>";
            echo $this->devicecolour."</br>";
            echo $this->devicecondition."</br>";
            echo $this->devicememory."</br>";
            echo $this->IMEI."</br>";
            echo $this->warranty."</br>";

        }





}

class Iphone extends Device
{

    public function  GetDeviceInfo()
    {

        parent::GetDeviceInfo();

    }


}


class Ipad extends Device
{
    public $deviceconnection;

    public function SetDeviceConnection($deviceconnection)
    {
        $this->deviceconnection=$deviceconnection;
        return $this;

    }

    public function GetDeviceConnection()
    {
        return $this->deviceconnection;

    }

    public function GetDeviceInfo()
    {
        parent::GetDeviceInfo(); // TODO: Change the autogenerated stub

        echo $this->deviceconnection;
    }


}


Class Macbook extends Device
{
    public $Os;
    public $Retina;
    public $StorageType;
    public $Year;
    public $Display;
    public $Processor;


    public function SetOS($os)
    {
        $this->Os=$os;
        return $this;

    }

    public function GetOs()
    {
        return $this->Os;

    }


    public function SetRetina($retina)
    {
        if($retina==1)
        {
            $this->Retina = true;

        }else{

            $this->Retina = false;
        }
        return $this;
    }

    public function Getretina()
    {
        return $this->Retina;

    }

    public function SetStorageType($storagetype)
    {
        $this->StorageType=$storagetype;
        return $this;

    }

    public function GetSorageType()
    {
        return $this->StorageType;

    }

    public function SetYear($yeare)
    {
        $this->Year=$yeare;
        return $this;

    }

    public function GetYear()
    {
        return $this->Year;

    }

    public function SetDisplay($display)
    {
        $this->Display=$display;
        return $this;

    }

    public function GetDisplay()
    {
        return $this->Display;

    }

    public function SetProcessor($processor)
    {
        $this->Processor=$processor;
        return $this;

    }

    public function GetProcessor()
    {
        return $this->Processor;

    }



    public function  GetDeviceInfo()
    {

        parent::GetDeviceInfo();
        echo $this->$Os;
        echo $this-> $Retina;
        echo $this-> $StorageType;
        echo $this-> $Year;
        echo $this-> $Display;
        echo $this-> $Processor;


    }




}

class RebuyDevice extends Device
{







}